### ISSUE TITLE
acpid.socket: Permission denied

### ISSUE THREAD

**Issue by BenMoore71** [TarlogicSecurity/Chankro#1]
Getting acpid.socket: Permission denied error upon launching the php file.

**Comment by X-C3LL** [comment]
Maybe the problem is that we are using chmod() from the PHP (and if it is banned we can not give exec perms to the file). We are going to move the function inside the C library this weekend to avoid the issue.

**Comment by X-C3LL** [comment]
Hi @BenMoore71 !

I made a quick'n'dirty fix in this fork https://github.com/X-C3LL/Chankro . Try it and tell me if the problem is solved.

**Comment by TarlogicSecurity** [comment]
Updated the files, please try again and confirm if the problem was solved.
