### ISSUE TITLE
Wrong relative path behavior

### ISSUE THREAD

**Issue by noraj** [TarlogicSecurity/Chankro#3]
We packaged Chankro into [BlackArch](https://blackarch.org/) but Chankro has an issue in the way it handle relative path either for the output dir or for loading the hook.

see https://github.com/BlackArch/blackarch/issues/2342

**Comment by noraj** [comment]
You need to change either https://github.com/TarlogicSecurity/Chankro/blob/b5609214b4e92dc1fbfeac1ea864d0467f7191e2/chankro.py#L40 or/and https://github.com/TarlogicSecurity/Chankro/blob/b5609214b4e92dc1fbfeac1ea864d0467f7191e2/chankro.py#L53

**Comment by noraj** [comment]
I made PR https://github.com/TarlogicSecurity/Chankro/pull/4

Tested:

```
$ cat /usr/bin/chankro 
#!/bin/sh
exec python2 /usr/share/chankro/chankro.py "${@}"

$ chankro --arch 64 --input /tmp/script.sh --output chankro.php --path /var/www/html/upload


     -=[ Chankro ]=-
    -={ @TheXC3LL }=-


[+] Binary file: /tmp/script.sh
[+] Architecture: x64
[+] Final PHP: chankro.php


[+] File created!

$ chankro --arch 64 --input /tmp/script.sh --output /tmp/chankro.php --path /var/www/html/upload


     -=[ Chankro ]=-
    -={ @TheXC3LL }=-


[+] Binary file: /tmp/script.sh
[+] Architecture: x64
[+] Final PHP: /tmp/chankro.php


[+] File created!
```

**Comment by TarlogicSecurity** [comment]
Hi noraj,

Thank you for the PR!
